CITIES_LIST = [
    {"label": "Delhi", "value": "Delhi"},
    {"label": "Ambala", "value": "Ambala"},
    {"label": "Bhiwani", "value": "Bhiwani"},
    {"label": "Faridabad", "value": "Faridabad"},
    {"label": "Fatehabad", "value": "Fatehabad"},
    {"label": "Gurgaon", "value": "Gurgaon"},
    {"label": "Hisar", "value": "Hisar"},
    {"label": "Jhajjar", "value": "Jhajjar"},
    {"label": "Jind", "value": "Jind"},
    {"label": "Kaithal", "value": "Kaithal"},
    {"label": "Karnal", "value": "Karnal"},
    {"label": "Kurukshetra", "value": "Kurukshetra"},
    {"label": "Mahendragarh", "value": "Mahendragarh"},
    {"label": "Nuh", "value": "Nuh"},
    {"label": "Palwal", "value": "Palwal"},
    {"label": "Panchkula", "value": "Panchkula"},
    {"label": "Panipat", "value": "Panipat"},
    {"label": "Rewari", "value": "Rewari"},
    {"label": "Rohtak", "value": "Rohtak"},
    {"label": "Sirsa", "value": "Sirsa"},
    {"label": "Sonipat", "value": "Sonipat"},
    {"label": "Yamunanagar", "value": "Yamunanagar"}
]
